version: '3'

services:
    bot:
        build: ./bot
        env_file:
        - ./bot/.env
    archivist:
        build: ./archivist
        env_file:
        - ./archivist/.env
    api:
        build: ./api
        env_file:
        - ./api/.env
        labels:
        - "traefik.frontend.rule=Host:api.localhost"
    portainer:
        volumes:
        - /usr/local/var/portainer:/data
        labels:
        - "traefik.frontend.rule=Host:portainer.localhost"
    traefik:
        volumes:
        - /var/run/docker.sock:/var/run/docker.sock
        - ./config/traefik.toml:/traefik.toml
        labels:
        - "traefik.frontend.rule=Host:traefik.localhost"
    redis:
        image: "bitnami/redis:latest"
        environment:
        - ALLOW_EMPTY_PASSWORD=yes
        ports:
        - "6379:6379"
