version: '3'

services:
    bot:
        image: gempir/logstvbot
    archivist:
        image: gempir/logstvarchivist
    api:
        image: gempir/logstvapi
        ports:
        - "8010:8010"
        labels:
        - "traefik.frontend.rule=Host:api.logs.tv"
        - "traefik.enable=true"
        - "traefik.port=8010"
    portainer:
        image: portainer/portainer
        command: -H unix:///var/run/docker.sock
        volumes:
        - /var/run/docker.sock:/var/run/docker.sock
        - /var/portainer:/data
        labels:
        - "traefik.backend=portainer"
        - "traefik.frontend.rule=Host:portainer.logs.tv"
        - "traefik.enable=true"
        - "traefik.port=9000"
    traefik:
        image: traefik
        command: --api --docker
        ports:
        - "80:80"
        - "443:443"
        volumes:
        - /var/run/docker.sock:/var/run/docker.sock
        - /var/traefik/traefik.toml:/traefik.toml
        labels:
        - "traefik.frontend.rule=Host:traefik.logs.tv"
        - "traefik.port=8080"
