---
- name: Provision hosts for logstv
  hosts: all
  remote_user: root
  
  roles:
    - {role: 'common', tags: 'common'}
    - {role: 'geerlingguy.java', tags: 'java'}
    - {role: 'cassandra', tags: 'cassandra'}
    - {role: 'relaybroker', tags: 'relaybroker'}
    - {role: 'bot', tags: 'bot'}
    - {role: 'api', tags: 'api'}
    - {role: 'api_nginx', tags: 'api_nginx'}
