---
  - name: Install Api Service
    template: src=templates/service.j2 dest=/etc/systemd/system/logstvapi.service

  - name: Start Api Service
    systemd: state=started name=logstvapi daemon_reload=yes