---
- name: create directory
  file:
    path: /var/logstv
    state: directory
    owner: root
    group: docker
    mode: 0740
    
- name: create bot env file
  template:
    src: templates/env.j2
    dest: /var/logstv/bot.env
    owner: root
    group: docker
    mode: 0640